// Generated by CoffeeScript 1.9.0
'use strict';
ash.fsm.DynamicComponentProvider = (function() {

  /**
   * @type {Object}
   */
  DynamicComponentProvider.prototype._closure = null;


  /**
   * @constructor
   * @param {Object} closure The function that will return the component instance when called.
   */

  function DynamicComponentProvider(closure) {
    this._closure = closure;
  }


  /**
    * Used to request a component from this provider
    *
    * @return {Object} The instance
   */

  DynamicComponentProvider.prototype.getComponent = function() {
    return this._closure;
  };


  /**
   * Used to compare this provider with others. Any provider that returns the same component
   * instance will be regarded as equivalent.
   *
   * @return {Object} The instance
   */

  Object.defineProperties(DynamicComponentProvider.prototype, {
    identifier: {
      get: function() {
        return this._closure;
      }
    }
  });

  return DynamicComponentProvider;

})();
