// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.AnimationNode = (function(superClass) {
    extend(AnimationNode, superClass);

    function AnimationNode() {
      return AnimationNode.__super__.constructor.apply(this, arguments);
    }

    AnimationNode.components = {
      animation: asteroids.components.Animation
    };

    AnimationNode.prototype.animation = null;

    return AnimationNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=animation_node.js.map
