// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  asteroids.nodes.AnimationNode = (function(_super) {
    __extends(AnimationNode, _super);

    function AnimationNode() {
      return AnimationNode.__super__.constructor.apply(this, arguments);
    }

    AnimationNode.className = 'AnimationNode';

    AnimationNode.components = {
      animation: asteroids.components.Animation
    };

    AnimationNode.prototype.animation = null;

    return AnimationNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=animation_node.js.map
