// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.AsteroidCollisionNode = (function(superClass) {
    extend(AsteroidCollisionNode, superClass);

    function AsteroidCollisionNode() {
      return AsteroidCollisionNode.__super__.constructor.apply(this, arguments);
    }

    AsteroidCollisionNode.components = {
      asteroid: asteroids.components.Asteroid,
      position: asteroids.components.Position,
      collision: asteroids.components.Collision,
      audio: asteroids.components.Audio
    };

    AsteroidCollisionNode.prototype.asteroid = null;

    AsteroidCollisionNode.prototype.position = null;

    AsteroidCollisionNode.prototype.collision = null;

    AsteroidCollisionNode.prototype.audio = null;

    return AsteroidCollisionNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=asteroid_collision_node.js.map
