// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.AudioNode = (function(superClass) {
    extend(AudioNode, superClass);

    function AudioNode() {
      return AudioNode.__super__.constructor.apply(this, arguments);
    }

    AudioNode.components = {
      audio: asteroids.components.Audio
    };

    AudioNode.prototype.audio = null;

    return AudioNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=audio_node.js.map
