// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /*
    * @constructor
   */
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  asteroids.nodes.AudioNode = (function(_super) {
    __extends(AudioNode, _super);

    function AudioNode() {
      return AudioNode.__super__.constructor.apply(this, arguments);
    }


    /** @type {string} */

    AudioNode.className = 'AudioNode';


    /** @type {Object.<string, Function} */

    AudioNode.components = {
      audio: asteroids.components.Audio
    };


    /** @type {asteroids.components.Audio} */

    AudioNode.prototype.audio = null;

    return AudioNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=audio_node.js.map
