// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  asteroids.nodes.BulletAgeNode = (function(_super) {
    __extends(BulletAgeNode, _super);

    function BulletAgeNode() {
      return BulletAgeNode.__super__.constructor.apply(this, arguments);
    }

    BulletAgeNode.classnName = 'BulletAgeNode';

    BulletAgeNode.components = {
      bullet: asteroids.components.Bullet
    };

    BulletAgeNode.prototype.bullet = null;

    return BulletAgeNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=bullet_age_node.js.map
