// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.BulletCollisionNode = (function(superClass) {
    extend(BulletCollisionNode, superClass);

    function BulletCollisionNode() {
      return BulletCollisionNode.__super__.constructor.apply(this, arguments);
    }

    BulletCollisionNode.components = {
      bullet: asteroids.components.Bullet,
      position: asteroids.components.Position,
      collision: asteroids.components.Collision
    };

    BulletCollisionNode.prototype.bullet = null;

    BulletCollisionNode.prototype.position = null;

    BulletCollisionNode.prototype.collision = null;

    return BulletCollisionNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=bullet_collision_node.js.map
