// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.DeathThroesNode = (function(superClass) {
    extend(DeathThroesNode, superClass);

    function DeathThroesNode() {
      return DeathThroesNode.__super__.constructor.apply(this, arguments);
    }

    DeathThroesNode.components = {
      death: asteroids.components.DeathThroes
    };

    DeathThroesNode.prototype.death = null;

    return DeathThroesNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=death_throes_node.js.map
