// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /*
    * @constructor
   */
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  asteroids.nodes.DeathThroesNode = (function(_super) {
    __extends(DeathThroesNode, _super);

    function DeathThroesNode() {
      return DeathThroesNode.__super__.constructor.apply(this, arguments);
    }


    /** @type {string} */

    DeathThroesNode.className = 'DeathThroesNode';


    /** @type {Object.<string, Function} */

    DeathThroesNode.components = {
      death: asteroids.components.DeathThroes
    };


    /** @type {asteroids.components.DeathThroes} */

    DeathThroesNode.prototype.death = null;

    return DeathThroesNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=death_throes_node.js.map
