// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  asteroids.nodes.GameNode = (function(_super) {
    __extends(GameNode, _super);

    function GameNode() {
      return GameNode.__super__.constructor.apply(this, arguments);
    }

    GameNode.className = 'GameNode';

    GameNode.components = {
      state: asteroids.components.GameState
    };

    GameNode.prototype.state = null;

    return GameNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=game_node.js.map
