// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.GameNode = (function(superClass) {
    extend(GameNode, superClass);

    function GameNode() {
      return GameNode.__super__.constructor.apply(this, arguments);
    }

    GameNode.components = {
      state: asteroids.components.GameState
    };

    GameNode.prototype.state = null;

    return GameNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=game_node.js.map
