// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.HudNode = (function(superClass) {
    extend(HudNode, superClass);

    function HudNode() {
      return HudNode.__super__.constructor.apply(this, arguments);
    }

    HudNode.components = {
      state: asteroids.components.GameState,
      hud: asteroids.components.Hud
    };

    HudNode.prototype.state = null;

    HudNode.prototype.hud = null;

    return HudNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=hud_node.js.map
