// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  asteroids.nodes.HudNode = (function(_super) {
    __extends(HudNode, _super);

    function HudNode() {
      return HudNode.__super__.constructor.apply(this, arguments);
    }

    HudNode.className = 'HudNode';

    HudNode.components = {
      state: asteroids.components.GameState,
      hud: asteroids.components.Hud
    };

    HudNode.prototype.state = null;

    HudNode.prototype.hud = null;

    return HudNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=hud_node.js.map
