// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.MotionControlNode = (function(superClass) {
    extend(MotionControlNode, superClass);

    function MotionControlNode() {
      return MotionControlNode.__super__.constructor.apply(this, arguments);
    }

    MotionControlNode.components = {
      control: asteroids.components.MotionControls,
      position: asteroids.components.Position,
      motion: asteroids.components.Motion
    };

    MotionControlNode.prototype.control = null;

    MotionControlNode.prototype.position = null;

    MotionControlNode.prototype.motion = null;

    return MotionControlNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=motion_control_node.js.map
