// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.MovementNode = (function(superClass) {
    extend(MovementNode, superClass);

    function MovementNode() {
      return MovementNode.__super__.constructor.apply(this, arguments);
    }

    MovementNode.components = {
      position: asteroids.components.Position,
      motion: asteroids.components.Motion
    };

    MovementNode.prototype.position = null;

    MovementNode.prototype.motion = null;

    return MovementNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=movement_node.js.map
