// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /*
    * @constructor
   */
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  asteroids.nodes.RenderNode = (function(_super) {
    __extends(RenderNode, _super);

    function RenderNode() {
      return RenderNode.__super__.constructor.apply(this, arguments);
    }


    /** @type {string} */

    RenderNode.className = 'RenderNode';


    /** @type {Object.<string, Function} */

    RenderNode.components = {
      position: asteroids.components.Position,
      display: asteroids.components.Display
    };


    /** @type {asteroids.components.Position} */

    RenderNode.prototype.position = null;


    /** @type {asteroids.components.Display} */

    RenderNode.prototype.display = null;

    return RenderNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=render_node.js.map
