// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /*
    * @constructor
   */
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  asteroids.nodes.SpaceshipNode = (function(_super) {
    __extends(SpaceshipNode, _super);

    function SpaceshipNode() {
      return SpaceshipNode.__super__.constructor.apply(this, arguments);
    }


    /** @type {string} */

    SpaceshipNode.className = 'SpaceshipNode';


    /** @type {Object.<string, Function} */

    SpaceshipNode.components = {
      spaceship: asteroids.components.Spaceship,
      position: asteroids.components.Position
    };


    /** @type {asteroids.components.Spaceship} */

    SpaceshipNode.prototype.spaceship = null;


    /** @type {asteroids.components.Position} */

    SpaceshipNode.prototype.position = null;

    return SpaceshipNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=spaceship_node.js.map
