// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.SpaceshipNode = (function(superClass) {
    extend(SpaceshipNode, superClass);

    function SpaceshipNode() {
      return SpaceshipNode.__super__.constructor.apply(this, arguments);
    }

    SpaceshipNode.components = {
      spaceship: asteroids.components.Spaceship,
      position: asteroids.components.Position
    };

    SpaceshipNode.prototype.spaceship = 0;

    SpaceshipNode.prototype.position = 0;

    return SpaceshipNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=spaceship_node.js.map
