// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /*
    * @constructor
   */
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  asteroids.nodes.SpaceshipCollisionNode = (function(_super) {
    __extends(SpaceshipCollisionNode, _super);

    function SpaceshipCollisionNode() {
      return SpaceshipCollisionNode.__super__.constructor.apply(this, arguments);
    }


    /** @type {string} */

    SpaceshipCollisionNode.className = 'SpaceshipCollisionNode';


    /** @type {Object.<string, Function} */

    SpaceshipCollisionNode.components = {
      spaceship: asteroids.components.Spaceship,
      position: asteroids.components.Position,
      collision: asteroids.components.Collision,
      audio: asteroids.components.Audio
    };


    /** @type {asteroids.components.Spaceship} */

    SpaceshipCollisionNode.prototype.spaceship = null;


    /** @type {asteroids.components.Position} */

    SpaceshipCollisionNode.prototype.position = null;


    /** @type {asteroids.components.Collision} */

    SpaceshipCollisionNode.prototype.collision = null;


    /** @type {asteroids.components.Audio} */

    SpaceshipCollisionNode.prototype.audio = null;

    return SpaceshipCollisionNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=spaceship_collision_node.js.map
