// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.SpaceshipCollisionNode = (function(superClass) {
    extend(SpaceshipCollisionNode, superClass);

    function SpaceshipCollisionNode() {
      return SpaceshipCollisionNode.__super__.constructor.apply(this, arguments);
    }

    SpaceshipCollisionNode.components = {
      spaceship: asteroids.components.Spaceship,
      position: asteroids.components.Position,
      collision: asteroids.components.Collision,
      audio: asteroids.components.Audio
    };

    SpaceshipCollisionNode.prototype.spaceship = 0;

    SpaceshipCollisionNode.prototype.position = 0;

    SpaceshipCollisionNode.prototype.collision = null;

    SpaceshipCollisionNode.prototype.audio = null;

    return SpaceshipCollisionNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=spaceship_collision_node.js.map
