// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  asteroids.nodes.WaitForStartNode = (function(_super) {
    __extends(WaitForStartNode, _super);

    function WaitForStartNode() {
      return WaitForStartNode.__super__.constructor.apply(this, arguments);
    }

    WaitForStartNode.className = 'WaitForStartNode';

    WaitForStartNode.components = {
      wait: asteroids.components.WaitForStart
    };

    WaitForStartNode.prototype.wait = null;

    return WaitForStartNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=wait_for_start_node.js.map
