// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  asteroids.nodes.WaitForStartNode = (function(superClass) {
    extend(WaitForStartNode, superClass);

    function WaitForStartNode() {
      return WaitForStartNode.__super__.constructor.apply(this, arguments);
    }

    WaitForStartNode.components = {
      wait: asteroids.components.WaitForStart
    };

    WaitForStartNode.prototype.wait = null;

    return WaitForStartNode;

  })(ash.core.Node);

}).call(this);

//# sourceMappingURL=wait_for_start_node.js.map
