// Generated by CoffeeScript 1.9.0

/*
 * An internal class for a linked list of entities. Used inside the framework for
 * managing the entities.
 */
'use strict';

/**
 * @constructor
 */
ash.core.EntityList = (function() {
  function EntityList() {}


  /**
   * @type {ash.core.Entity}
   */

  EntityList.prototype.head = null;


  /**
   * @type {ash.core.Entity}
   */

  EntityList.prototype.tail = null;


  /**
   * Add an entity to the list
   *
   * @param {ash.core.Entity}
   */

  EntityList.prototype.add = function(entity) {
    if (!this.head) {
      this.head = this.tail = entity;
      entity.next = entity.previous = null;
    } else {
      this.tail.next = entity;
      entity.previous = this.tail;
      entity.next = null;
      this.tail = entity;
    }
  };


  /**
   * Remove an entity from the list
   *
   * @param {ash.core.Entity}
   */

  EntityList.prototype.remove = function(entity) {
    if (this.head === entity) {
      this.head = this.head.next;
    }
    if (this.tail === entity) {
      this.tail = this.tail.previous;
    }
    if (entity.previous) {
      entity.previous.next = entity.next;
    }
    if (entity.next) {
      entity.next.previous = entity.previous;
    }
  };


  /**
   * Remove all entities
   */

  EntityList.prototype.removeAll = function() {
    var entity;
    while (this.head) {
      entity = this.head;
      this.head = this.head.next;
      entity.previous = null;
      entity.next = null;
    }
    this.tail = null;
  };

  return EntityList;

})();

//# sourceMappingURL=EntityList.js.map
