// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  ash.core.Node = (function() {
    function Node() {}

    Node.prototype.entity = null;

    Node.prototype.previous = null;

    Node.prototype.next = null;

    return Node;

  })();

}).call(this);

//# sourceMappingURL=Node.js.map
