// Generated by CoffeeScript 1.9.0
'use strict';

/**
 * @constructor
 */
ash.core.Node = (function() {
  function Node() {}


  /**
   * @type {ash.core.Entity}
   */

  Node.prototype.entity = null;


  /**
   * @type {ash.core.Node}
   */

  Node.prototype.previous = null;


  /**
   * @type {ash.core.Node}
   */

  Node.prototype.next = null;

  return Node;

})();

//# sourceMappingURL=Node.js.map
