// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.graphics.AsteroidView = (function() {
    AsteroidView.prototype.x = 0;

    AsteroidView.prototype.y = 0;

    AsteroidView.prototype.width = 0;

    AsteroidView.prototype.height = 0;

    AsteroidView.prototype.rotation = 0;

    AsteroidView.prototype.graphic = null;

    AsteroidView.prototype.radius = 0;

    AsteroidView.prototype.points = null;

    AsteroidView.prototype.count = 0;

    function AsteroidView(graphic1, radius) {
      var angle, length, posX, posY;
      this.graphic = graphic1;
      this.radius = radius;
      this.width = this.radius;
      this.height = this.radius;
      this.points = [];
      angle = 0;
      while (angle < Math.PI * 2) {
        length = (0.75 + Math.random() * 0.25) * this.radius;
        posX = Math.cos(angle) * length;
        posY = Math.sin(angle) * length;
        this.points.push({
          x: posX,
          y: posY
        });
        angle += Math.random() * 0.5;
      }
    }

    AsteroidView.prototype.draw = function() {
      var graphic, i;
      graphic = this.graphic;
      graphic.save();
      graphic.beginPath();
      graphic.translate(this.x, this.y);
      graphic.rotate(this.rotation);
      graphic.fillStyle = "#FFFFFF";
      graphic.moveTo(this.radius, 0);
      i = 0;
      while (i < this.points.length) {
        graphic.lineTo(this.points[i].x, this.points[i].y);
        ++i;
      }
      graphic.lineTo(this.radius, 0);
      graphic.fill();
      graphic.restore();
    };

    return AsteroidView;

  })();

}).call(this);

//# sourceMappingURL=asteroid_view.js.map
