// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var Dot, Point;

  Point = asteroids.ui.Point;

  asteroids.graphics.AsteroidDeathView = (function() {
    var numDots;

    numDots = 8;

    AsteroidDeathView.prototype.dots = null;

    AsteroidDeathView.prototype.x = 0;

    AsteroidDeathView.prototype.y = 0;

    AsteroidDeathView.prototype.width = 0;

    AsteroidDeathView.prototype.height = 0;

    AsteroidDeathView.prototype.rotation = 0;

    AsteroidDeathView.prototype.graphic = null;

    AsteroidDeathView.prototype.radius = 0;

    AsteroidDeathView.prototype.points = null;

    AsteroidDeathView.prototype.count = 0;

    AsteroidDeathView.prototype.first = true;

    function AsteroidDeathView(graphic1, radius) {
      this.graphic = graphic1;
      this.radius = radius;
      this.dots = [];
    }

    AsteroidDeathView.prototype.animate = function(time) {
      var dot, i, j, k, len, ref, ref1;
      if (this.first) {
        this.first = false;
        for (i = j = 0, ref = numDots; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
          dot = new Dot(this.graphic, this.radius);
          this.dots.push(dot);
        }
      }
      ref1 = this.dots;
      for (k = 0, len = ref1.length; k < len; k++) {
        dot = ref1[k];
        dot.x += dot.velocity.x * time;
        dot.y += dot.velocity.y * time;
      }
      return this.draw();
    };

    AsteroidDeathView.prototype.draw = function() {
      var dot, j, len, ref, results;
      ref = this.dots;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        dot = ref[j];
        results.push(dot.draw(this.x, this.y));
      }
      return results;
    };

    return AsteroidDeathView;

  })();

  Dot = (function() {
    Dot.prototype.velocity = null;

    Dot.prototype.graphic = null;

    Dot.prototype.x1 = 0;

    Dot.prototype.y1 = 0;

    Dot.prototype.x = 0;

    Dot.prototype.y = 0;

    function Dot(graphic1, maxDistance) {
      var angle, distance, speed;
      this.graphic = graphic1;
      angle = Math.random() * 2 * Math.PI;
      distance = Math.random() * maxDistance;
      this.x = Math.cos(angle) * distance;
      this.y = Math.sin(angle) * distance;
      speed = Math.random() * 10 + 10;
      this.velocity = new Point(Math.cos(angle) * speed, Math.sin(angle) * speed);
    }

    Dot.prototype.draw = function(x, y) {
      var graphic;
      graphic = this.graphic;
      graphic.save();
      graphic.beginPath();
      graphic.translate(x, y);
      graphic.rotate(this.rotation);
      graphic.fillStyle = "#FFFFFF";
      graphic.arc(this.x, this.y, 2, 0, Math.PI * 2, false);
      graphic.fill();
      graphic.restore();
    };

    return Dot;

  })();

}).call(this);

//# sourceMappingURL=asteroid_death_view.js.map
