// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.graphics.BulletView = (function() {
    BulletView.prototype.x = 0;

    BulletView.prototype.y = 0;

    BulletView.prototype.width = 4;

    BulletView.prototype.height = 4;

    BulletView.prototype.rotation = 0;

    BulletView.prototype.graphic = null;

    function BulletView(graphic1) {
      this.graphic = graphic1;
    }

    BulletView.prototype.draw = function() {
      var graphic;
      graphic = this.graphic;
      graphic.save();
      graphic.beginPath();
      graphic.rotate(this.rotation);
      graphic.fillStyle = "#FFFFFF";
      graphic.arc(this.x, this.y, 2, 0, Math.PI * 2, false);
      graphic.fill();
      graphic.restore();
    };

    return BulletView;

  })();

}).call(this);

//# sourceMappingURL=bullet_view.js.map
