// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  asteroids.graphics.HudView = (function() {

    /** @type {number} */
    HudView.prototype.x = 0;


    /** @type {number} */

    HudView.prototype.y = 0;


    /** @type {number} */

    HudView.prototype.width = 4;


    /** @type {number} */

    HudView.prototype.height = 4;


    /** @type {number} */

    HudView.prototype.rotation = 0;


    /** @type {CanvasRenderingContext2D} */

    HudView.prototype.graphic = null;


    /** @type {number} */

    HudView.prototype.score = 0;


    /** @type {number} */

    HudView.prototype.lives = 3;


    /** @type {Function} */

    HudView.prototype.drawScore = null;


    /** @type {Function} */

    HudView.prototype.drawLives = null;


    /**
     * @constructor
     * @param {CanvasRenderingContext2D}
     */

    function HudView(_at_graphic) {
      this.graphic = _at_graphic;
      this.setScore = __bind(this.setScore, this);
      this.setLives = __bind(this.setLives, this);
      this.draw = __bind(this.draw, this);
      this.drawScore = this.createScore;
      this.drawLives = this.createLives;
    }


    /**
     * draw the view
     */

    HudView.prototype.draw = function() {
      this.drawScore();
      this.drawLives();
    };


    /**
     * @param {number}
     */

    HudView.prototype.setLives = function(lives) {
      return this.lives = lives;
    };


    /**
     * @param {number}
     */

    HudView.prototype.setScore = function(score) {
      return this.score = score;
    };


    /**
     * draw the lives display
     */

    HudView.prototype.createLives = function() {
      var l, s, x, y;
      this.graphic.save();
      this.graphic.beginPath();
      this.graphic.font = 'bold 18px Helvetica';
      this.graphic.fillStyle = '#FFFFFF';
      this.graphic.textAlign = 'center';
      s = "LIVES: " + this.lives;
      l = this.graphic.measureText(s);
      x = l.width;
      y = 20;
      this.graphic.fillText(s, x, y);
      this.graphic.fill();
      this.graphic.restore();
    };


    /**
     * draw the score display
     */

    HudView.prototype.createScore = function() {
      var l, s, x, y;
      this.graphic.save();
      this.graphic.beginPath();
      this.graphic.font = 'bold 18px Helvetica';
      this.graphic.fillStyle = '#FFFFFF';
      this.graphic.textAlign = 'center';
      s = "SCORE: " + this.score;
      l = this.graphic.measureText(s);
      x = (window.window.innerWidth * window.devicePixelRatio) - l.width;
      y = 20;
      this.graphic.fillText(s, x, y);
      this.graphic.fill();
      this.graphic.restore();
    };

    return HudView;

  })();

}).call(this);

//# sourceMappingURL=hud_view.js.map
