// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  asteroids.graphics.HudView = (function() {
    HudView.prototype.x = 0;

    HudView.prototype.y = 0;

    HudView.prototype.width = 4;

    HudView.prototype.height = 4;

    HudView.prototype.rotation = 0;

    HudView.prototype.graphic = null;

    HudView.prototype.score = 0;

    HudView.prototype.lives = 3;

    HudView.prototype.drawScore = null;

    HudView.prototype.drawLives = null;

    function HudView(graphic) {
      this.graphic = graphic;
      this.setScore = bind(this.setScore, this);
      this.setLives = bind(this.setLives, this);
      this.draw = bind(this.draw, this);
      this.drawScore = this.createScore;
      this.drawLives = this.createLives;
    }

    HudView.prototype.draw = function() {
      this.drawScore();
      this.drawLives();
    };

    HudView.prototype.setLives = function(lives) {
      return this.lives = lives;
    };

    HudView.prototype.setScore = function(score) {
      return this.score = score;
    };

    HudView.prototype.createLives = function() {
      var l, s, x, y;
      this.graphic.save();
      this.graphic.beginPath();
      this.graphic.font = 'bold 18px Helvetica';
      this.graphic.fillStyle = '#FFFFFF';
      this.graphic.textAlign = 'center';
      s = "LIVES: " + this.lives;
      l = this.graphic.measureText(s);
      x = l.width;
      y = 20;
      this.graphic.fillText(s, x, y);
      this.graphic.fill();
      this.graphic.restore();
    };

    HudView.prototype.createScore = function() {
      var l, s, x, y;
      this.graphic.save();
      this.graphic.beginPath();
      this.graphic.font = 'bold 18px Helvetica';
      this.graphic.fillStyle = '#FFFFFF';
      this.graphic.textAlign = 'center';
      s = "SCORE: " + this.score;
      l = this.graphic.measureText(s);
      x = (window.window.innerWidth * window.devicePixelRatio) - l.width;
      y = 20;
      this.graphic.fillText(s, x, y);
      this.graphic.fill();
      this.graphic.restore();
    };

    return HudView;

  })();

}).call(this);

//# sourceMappingURL=hud_view.js.map
