// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var Point;

  Point = asteroids.ui.Point;

  asteroids.graphics.SpaceshipDeathView = (function() {

    /** @type {number} */
    SpaceshipDeathView.prototype.x = 0;


    /** @type {number} */

    SpaceshipDeathView.prototype.y = 0;


    /** @type {number} */

    SpaceshipDeathView.prototype.width = 20;


    /** @type {number} */

    SpaceshipDeathView.prototype.height = 20;


    /** @type {number} */

    SpaceshipDeathView.prototype.rotation = 0;


    /** @type {CanvasRenderingContext2D} */

    SpaceshipDeathView.prototype.graphic = null;


    /** @type {asteroids.ui.Point} */

    SpaceshipDeathView.prototype.vel1 = null;


    /** @type {asteroids.ui.Point} */

    SpaceshipDeathView.prototype.vel2 = null;


    /** @type {number} */

    SpaceshipDeathView.prototype.rot1 = null;


    /** @type {number} */

    SpaceshipDeathView.prototype.rot2 = null;


    /** @type {number} */

    SpaceshipDeathView.prototype.x1 = 0;


    /** @type {number} */

    SpaceshipDeathView.prototype.y2 = 0;


    /** @type {number} */

    SpaceshipDeathView.prototype.y1 = 0;


    /** @type {number} */

    SpaceshipDeathView.prototype.y2 = 0;


    /** @type {boolean} */

    SpaceshipDeathView.prototype.first = true;


    /**
     * @constructor
     * @param {CanvasRenderingContext2D}
     */

    function SpaceshipDeathView(_at_graphic) {
      this.graphic = _at_graphic;
    }


    /**
     * @param {number}
     */

    SpaceshipDeathView.prototype.animate = function(time) {
      if (this.first) {
        this.first = false;
        this.vel1 = new Point(Math.random() * 10 - 5, Math.random() * 10 + 10);
        this.vel2 = new Point(Math.random() * 10 - 5, -(Math.random() * 10 + 10));
        this.rot1 = Math.random() * 300 - 150;
        this.rot2 = Math.random() * 300 - 150;
        this.x1 = this.x2 = this.x;
        this.y1 = this.y2 = this.y;
        this.r1 = this.r2 = this.rotation;
      }
      this.x1 += this.vel1.x * time;
      this.y1 += this.vel1.y * time;
      this.r1 += this.rot1 * time;
      this.x2 += this.vel2.x * time;
      this.y2 += this.vel2.y * time;
      this.r2 += this.rot2 * time;
      return this.draw();
    };


    /**
     * draw the view
     */

    SpaceshipDeathView.prototype.draw = function() {
      var graphic;
      graphic = this.graphic;
      graphic.save();
      graphic.beginPath();
      graphic.translate(this.x + this.x1, this.y + this.y1);
      graphic.rotate(this.r1);
      graphic.fillStyle = "#FFFFFF";
      graphic.moveTo(10, 0);
      graphic.lineTo(-7, 7);
      graphic.lineTo(-4, 0);
      graphic.lineTo(10, 0);
      graphic.fill();
      graphic.restore();
      graphic.save();
      graphic.beginPath();
      graphic.translate(this.x + this.x2, this.y + this.y2);
      graphic.rotate(this.r2);
      graphic.fillStyle = "#FFFFFF";
      graphic.moveTo(10, 0);
      graphic.lineTo(-7, 7);
      graphic.lineTo(-4, 0);
      graphic.lineTo(10, 0);
      graphic.fill();
      graphic.restore();
    };

    return SpaceshipDeathView;

  })();

}).call(this);

//# sourceMappingURL=spaceship_death_view.js.map
