// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.graphics.SpaceshipView = (function() {

    /** @type {number} */
    SpaceshipView.prototype.x = 0;


    /** @type {number} */

    SpaceshipView.prototype.y = 0;


    /** @type {number} */

    SpaceshipView.prototype.width = 20;


    /** @type {number} */

    SpaceshipView.prototype.height = 20;


    /** @type {number} */

    SpaceshipView.prototype.rotation = 0;


    /** @type {CanvasRenderingContext2D} */

    SpaceshipView.prototype.graphic = null;


    /**
     * @constructor
     * @param {CanvasRenderingContext2D}
     */

    function SpaceshipView(_at_graphic) {
      this.graphic = _at_graphic;
    }


    /**
     * draw the view
     */

    SpaceshipView.prototype.draw = function() {
      var graphic;
      graphic = this.graphic;
      graphic.save();
      graphic.beginPath();
      graphic.translate(this.x, this.y);
      graphic.rotate(this.rotation);
      graphic.fillStyle = "#FFFFFF";
      graphic.moveTo(10, 0);
      graphic.lineTo(-7, 7);
      graphic.lineTo(-4, 0);
      graphic.lineTo(-7, -7);
      graphic.lineTo(10, 0);
      graphic.fill();
      graphic.restore();
    };

    return SpaceshipView;

  })();

}).call(this);

//# sourceMappingURL=spaceship_view.js.map
