// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.graphics.SpaceshipView = (function() {
    SpaceshipView.prototype.x = 0;

    SpaceshipView.prototype.y = 0;

    SpaceshipView.prototype.width = 20;

    SpaceshipView.prototype.height = 20;

    SpaceshipView.prototype.rotation = 0;

    SpaceshipView.prototype.graphic = null;

    function SpaceshipView(_at_graphic) {
      this.graphic = _at_graphic;
    }

    SpaceshipView.prototype.draw = function() {
      var graphic;
      graphic = this.graphic;
      graphic.save();
      graphic.beginPath();
      graphic.translate(this.x, this.y);
      graphic.rotate(this.rotation);
      graphic.fillStyle = "#FFFFFF";
      graphic.moveTo(10, 0);
      graphic.lineTo(-7, 7);
      graphic.lineTo(-4, 0);
      graphic.lineTo(-7, -7);
      graphic.lineTo(10, 0);
      graphic.fill();
      graphic.restore();
    };

    return SpaceshipView;

  })();

}).call(this);

//# sourceMappingURL=spaceship_view.js.map
