// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var Signal0;

  Signal0 = ash.signals.Signal0;

  asteroids.graphics.WaitForStartView = (function() {

    /** @type {number} */
    WaitForStartView.prototype.x = 0;


    /** @type {number} */

    WaitForStartView.prototype.y = 0;


    /** @type {number} */

    WaitForStartView.prototype.width = 4;


    /** @type {number} */

    WaitForStartView.prototype.height = 4;


    /** @type {number} */

    WaitForStartView.prototype.rotation = 0;


    /** @type {CanvasRenderingContext2D} */

    WaitForStartView.prototype.graphic = null;


    /** @type {Function} */

    WaitForStartView.prototype.gameOver = null;


    /** @type {Function} */

    WaitForStartView.prototype.clickToStart = null;


    /** @type {Function} */

    WaitForStartView.prototype.instructions = null;


    /** @type {ash.signals.Signal0} */

    WaitForStartView.prototype.click = null;


    /**
     * @constructor
     * @param {CanvasRenderingContext2D}
     */

    function WaitForStartView(_at_graphic) {
      this.graphic = _at_graphic;
      this.click = new Signal0();
      this.gameOver = this.createGameOver;
      this.instructions = this.createInstructions;
      this.clickToStart = this.createClickToStart;
      this.graphic.canvas.addEventListener('click', (function(_this) {
        return function(event) {
          return _this.click.dispatch();
        };
      })(this));
    }


    /**
     * draw the game over button
     */

    WaitForStartView.prototype.createGameOver = function() {
      var l, s, x, y;
      this.graphic.save();
      this.graphic.beginPath();
      this.graphic.font = 'bold 32px Helvetica';
      this.graphic.fillStyle = '#FFFFFF';
      s = 'ASTEROIDS';
      l = this.graphic.measureText(s);
      x = Math.floor(((window.innerWidth * window.devicePixelRatio) - l.width) / 2);
      y = 175;
      this.graphic.fillText(s, x, y);
      this.graphic.fill();
      this.graphic.restore();
    };


    /**
     * draw the start button
     */

    WaitForStartView.prototype.createClickToStart = function() {
      var l, s, x, y;
      this.graphic.save();
      this.graphic.beginPath();
      this.graphic.font = 'bold 18px Helvetica';
      this.graphic.fillStyle = '#FFFFFF';
      s = 'CLICK TO START';
      l = this.graphic.measureText(s);
      x = Math.floor(((window.innerWidth * window.devicePixelRatio) - l.width) / 2);
      y = 225;
      this.graphic.fillText(s, x, y);
      this.graphic.fill();
      this.graphic.restore();
    };


    /**
     * draw the instructions
     */

    WaitForStartView.prototype.createInstructions = function() {
      var l, s, x, y;
      this.graphic.save();
      this.graphic.beginPath();
      this.graphic.font = 'bold 14px Helvetica';
      this.graphic.fillStyle = '#FFFFFF';
      s = 'CTRL-Z to Fire  ~  Arrow Keys to Move';
      l = this.graphic.measureText(s);
      x = 10;
      y = window.innerHeight * window.devicePixelRatio - 20;
      this.graphic.fillText(s, x, y);
      this.graphic.fill();
      this.graphic.restore();
    };


    /**
     * draw the view
     */

    WaitForStartView.prototype.draw = function() {
      this.gameOver();
      this.clickToStart();
      this.instructions();
    };

    return WaitForStartView;

  })();

}).call(this);

//# sourceMappingURL=wait_for_start_view.js.map
