// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.Animation = (function() {
    Animation.className = 'Animation';

    Animation.prototype.animation = null;

    function Animation(_at_animation) {
      this.animation = _at_animation;
    }

    return Animation;

  })();

}).call(this);

//# sourceMappingURL=animation.js.map
