// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.components.Animation = (function() {
    Animation.prototype.animation = null;

    function Animation(animation) {
      this.animation = animation;
    }

    return Animation;

  })();

}).call(this);

//# sourceMappingURL=animation.js.map
