// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.components.Asteroid = (function() {
    Asteroid.prototype.fsm = null;

    function Asteroid(fsm) {
      this.fsm = fsm;
    }

    return Asteroid;

  })();

}).call(this);

//# sourceMappingURL=asteroid.js.map
