// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.Asteroid = (function() {

    /** @type {string} */
    Asteroid.className = 'Asteroid';


    /** @type {ash.fsm.EntityStateMachine} */

    Asteroid.prototype.fsm = null;


    /**
     * @constructor
     * @param {ash.fsm.EntityStateMachine}
     */

    function Asteroid(_at_fsm) {
      this.fsm = _at_fsm;
    }

    return Asteroid;

  })();

}).call(this);

//# sourceMappingURL=asteroid.js.map
