// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.Asteroid = (function() {
    Asteroid.className = 'Asteroid';

    Asteroid.prototype.fsm = null;

    function Asteroid(_at_fsm) {
      this.fsm = _at_fsm;
    }

    return Asteroid;

  })();

}).call(this);

//# sourceMappingURL=asteroid.js.map
