// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.Audio = (function() {

    /** @type {string} */
    Audio.className = 'Audio';


    /** @type {Array<Object>} */

    Audio.prototype.toPlay = null;


    /**
     * @constructor
     */

    function Audio() {
      this.toPlay = [];
    }


    /**
     * @param {Object}
     */

    Audio.prototype.play = function(sound) {
      return this.toPlay.push(sound);
    };

    return Audio;

  })();

}).call(this);

//# sourceMappingURL=audio.js.map
