// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.Audio = (function() {
    Audio.className = 'Audio';

    Audio.prototype.toPlay = null;

    function Audio() {
      this.toPlay = [];
    }

    Audio.prototype.play = function(sound) {
      return this.toPlay.push(sound);
    };

    return Audio;

  })();

}).call(this);

//# sourceMappingURL=audio.js.map
