// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.Bullet = (function() {

    /** @type {string} */
    Bullet.className = 'Bullet';


    /** @type {number} */

    Bullet.prototype.lifeRemaining = 0;


    /**
     * @constructor
     * @param {number}
     */

    function Bullet(_at_lifeRemaining) {
      this.lifeRemaining = _at_lifeRemaining;
    }

    return Bullet;

  })();

}).call(this);

//# sourceMappingURL=bullet.js.map
