// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.components.Bullet = (function() {
    Bullet.prototype.lifeRemaining = 0;

    function Bullet(lifeRemaining) {
      this.lifeRemaining = lifeRemaining;
    }

    return Bullet;

  })();

}).call(this);

//# sourceMappingURL=bullet.js.map
