// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.Collision = (function() {

    /** @type {string} */
    Collision.className = 'Collision';


    /** @type {number} */

    Collision.prototype.radius = 0;


    /**
     * @constructor
     * @param {number}
     */

    function Collision(_at_radius) {
      this.radius = _at_radius;
    }

    return Collision;

  })();

}).call(this);

//# sourceMappingURL=collision.js.map
