// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.components.Collision = (function() {
    Collision.prototype.radius = 0;

    function Collision(radius) {
      this.radius = radius;
    }

    return Collision;

  })();

}).call(this);

//# sourceMappingURL=collision.js.map
