// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.DeathThroes = (function() {

    /** @type {string} */
    DeathThroes.className = 'DeathThroes';


    /** @type {number} */

    DeathThroes.prototype.countdown = 0;


    /**
     * @constructor
     * @param {number}
     */

    function DeathThroes(duration) {
      this.countdown = duration;
    }

    return DeathThroes;

  })();

}).call(this);

//# sourceMappingURL=death_throes.js.map
