// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.components.DeathThroes = (function() {
    DeathThroes.prototype.countdown = 0;

    function DeathThroes(duration) {
      this.countdown = duration;
    }

    return DeathThroes;

  })();

}).call(this);

//# sourceMappingURL=death_throes.js.map
