// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.components.Display = (function() {
    Display.prototype.graphic = 0;

    function Display(graphic) {
      this.graphic = graphic;
    }

    return Display;

  })();

}).call(this);

//# sourceMappingURL=display.js.map
