// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.Display = (function() {
    Display.className = 'Display';

    Display.prototype.graphic = 0;

    function Display(_at_graphic) {
      this.graphic = _at_graphic;
    }

    return Display;

  })();

}).call(this);

//# sourceMappingURL=display.js.map
