// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.GameState = (function() {
    function GameState() {}


    /** @type {string} */

    GameState.className = 'GameState';


    /** @type {number} */

    GameState.prototype.lives = 3;


    /** @type {number} */

    GameState.prototype.level = 0;


    /** @type {number} */

    GameState.prototype.hits = 0;


    /** @type {boolean} */

    GameState.prototype.playing = false;


    /**
     * @constructor
     */

    GameState.prototype.setForStart = function() {
      this.lives = 3;
      this.level = 0;
      this.hits = 0;
      this.playing = true;
    };

    return GameState;

  })();

}).call(this);

//# sourceMappingURL=game_state.js.map
