// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.GameState = (function() {
    function GameState() {}

    GameState.className = 'GameState';

    GameState.prototype.lives = 3;

    GameState.prototype.level = 0;

    GameState.prototype.hits = 0;

    GameState.prototype.playing = false;

    GameState.prototype.setForStart = function() {
      this.lives = 3;
      this.level = 0;
      this.hits = 0;
      this.playing = true;
    };

    return GameState;

  })();

}).call(this);

//# sourceMappingURL=game_state.js.map
