// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var Point;

  Point = asteroids.ui.Point;

  asteroids.components.Gun = (function() {

    /** @type {string} */
    Gun.className = 'Gun';


    /** @type {boolean} */

    Gun.prototype.shooting = false;


    /** @type {number} */

    Gun.prototype.timeSinceLastShot = 0;


    /** @type {asteroids.ui.Point} */

    Gun.prototype.offsetFromParent = null;


    /** @type {number} */

    Gun.prototype.minimumShotInterval = 0;


    /** @type {number} */

    Gun.prototype.bulletLifetime = 0;


    /**
     * @constructor
     * @param {number}
     * @param {number}
     * @param {number}
     * @param {number}
     */

    function Gun(offsetX, offsetY, _at_minimumShotInterval, _at_bulletLifetime) {
      this.minimumShotInterval = _at_minimumShotInterval;
      this.bulletLifetime = _at_bulletLifetime;
      this.shooting = false;
      this.offsetFromParent = null;
      this.timeSinceLastShot = 0;
      this.offsetFromParent = new Point(offsetX, offsetY);
    }

    return Gun;

  })();

}).call(this);

//# sourceMappingURL=gun.js.map
