// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.GunControls = (function() {
    GunControls.className = 'GunControls';

    GunControls.prototype.trigger = 0;

    function GunControls(_at_trigger) {
      this.trigger = _at_trigger;
    }

    return GunControls;

  })();

}).call(this);

//# sourceMappingURL=gun_controls.js.map
