// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.components.GunControls = (function() {
    GunControls.prototype.trigger = 0;

    function GunControls(trigger) {
      this.trigger = trigger;
    }

    return GunControls;

  })();

}).call(this);

//# sourceMappingURL=gun_controls.js.map
