// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.Hud = (function() {
    Hud.className = 'Hud';

    Hud.prototype.view = null;

    function Hud(_at_view) {
      this.view = _at_view;
    }

    return Hud;

  })();

}).call(this);

//# sourceMappingURL=hud.js.map
