// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.components.Hud = (function() {
    Hud.prototype.view = null;

    function Hud(view) {
      this.view = view;
    }

    return Hud;

  })();

}).call(this);

//# sourceMappingURL=hud.js.map
