// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var Point;

  Point = asteroids.ui.Point;

  asteroids.components.Motion = (function() {
    Motion.className = 'Motion';

    Motion.prototype.velocity = null;

    Motion.prototype.angularVelocity = 0;

    Motion.prototype.damping = 0;

    function Motion(velocityX, velocityY, _at_angularVelocity, _at_damping) {
      this.angularVelocity = _at_angularVelocity;
      this.damping = _at_damping;
      this.velocity = new Point(velocityX, velocityY);
    }

    return Motion;

  })();

}).call(this);

//# sourceMappingURL=motion.js.map
