// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var Point;

  Point = asteroids.ui.Point;

  asteroids.components.Motion = (function() {
    Motion.prototype.velocity = null;

    Motion.prototype.angularVelocity = 0;

    Motion.prototype.damping = 0;

    function Motion(velocityX, velocityY, angularVelocity, damping) {
      this.angularVelocity = angularVelocity;
      this.damping = damping;
      this.velocity = new Point(velocityX, velocityY);
    }

    return Motion;

  })();

}).call(this);

//# sourceMappingURL=motion.js.map
