// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.components.MotionControls = (function() {
    MotionControls.prototype.left = 0;

    MotionControls.prototype.right = 0;

    MotionControls.prototype.accelerate = 0;

    MotionControls.prototype.accelerationRate = 0;

    MotionControls.prototype.rotationRate = 0;

    function MotionControls(left, right, accelerate, accelerationRate, rotationRate) {
      this.left = left;
      this.right = right;
      this.accelerate = accelerate;
      this.accelerationRate = accelerationRate;
      this.rotationRate = rotationRate;
    }

    return MotionControls;

  })();

}).call(this);

//# sourceMappingURL=motion_controls.js.map
