// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.MotionControls = (function() {
    MotionControls.className = 'MotionControls';

    MotionControls.prototype.left = 0;

    MotionControls.prototype.right = 0;

    MotionControls.prototype.accelerate = 0;

    MotionControls.prototype.accelerationRate = 0;

    MotionControls.prototype.rotationRate = 0;

    function MotionControls(_at_left, _at_right, _at_accelerate, _at_accelerationRate, _at_rotationRate) {
      this.left = _at_left;
      this.right = _at_right;
      this.accelerate = _at_accelerate;
      this.accelerationRate = _at_accelerationRate;
      this.rotationRate = _at_rotationRate;
    }

    return MotionControls;

  })();

}).call(this);

//# sourceMappingURL=motion_controls.js.map
