// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var Point;

  Point = asteroids.ui.Point;

  asteroids.components.Position = (function() {
    Position.className = 'Position';

    Position.prototype.position = null;

    Position.prototype.rotation = 0;

    function Position(x, y, _at_rotation) {
      this.rotation = _at_rotation;
      this.position = new Point(x, y);
    }

    return Position;

  })();

}).call(this);

//# sourceMappingURL=position.js.map
