// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var Point;

  Point = asteroids.ui.Point;

  asteroids.components.Position = (function() {

    /** @type {string} */
    Position.className = 'Position';


    /** @type {asteroids.ui.Point} */

    Position.prototype.position = null;


    /** @type {number} */

    Position.prototype.rotation = 0;


    /**
     * @constructor
     * @param {number}
     * @param {number}
     * @param {number}
     */

    function Position(x, y, _at_rotation) {
      this.rotation = _at_rotation;
      this.position = new Point(x, y);
    }

    return Position;

  })();

}).call(this);

//# sourceMappingURL=position.js.map
