// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var Point;

  Point = asteroids.ui.Point;

  asteroids.components.Position = (function() {
    Position.prototype.position = null;

    Position.prototype.rotation = 0;

    function Position(x, y, rotation) {
      this.rotation = rotation;
      this.position = new Point(x, y);
    }

    return Position;

  })();

}).call(this);

//# sourceMappingURL=position.js.map
