// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.Spaceship = (function() {

    /** @type {string} */
    Spaceship.className = 'Spaceship';


    /** @type {ash.fsm.EntityStateMachine} */

    Spaceship.prototype.fsm = null;


    /**
     * @constructor
     * @param {ash.fsm.EntityStateMachine}
     */

    function Spaceship(_at_fsm) {
      this.fsm = _at_fsm;
    }

    return Spaceship;

  })();

}).call(this);

//# sourceMappingURL=spaceship.js.map
