// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.components.Spaceship = (function() {
    Spaceship.className = 'Spaceship';

    Spaceship.prototype.fsm = null;

    function Spaceship(_at_fsm) {
      this.fsm = _at_fsm;
    }

    return Spaceship;

  })();

}).call(this);

//# sourceMappingURL=spaceship.js.map
