// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.components.Spaceship = (function() {
    Spaceship.prototype.fsm = null;

    function Spaceship(fsm) {
      this.fsm = fsm;
    }

    return Spaceship;

  })();

}).call(this);

//# sourceMappingURL=spaceship.js.map
