// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  asteroids.components.WaitForStart = (function() {
    WaitForStart.prototype.waitForStart = null;

    WaitForStart.prototype.startGame = false;

    function WaitForStart(waitForStart) {
      this.waitForStart = waitForStart;
      this.setStartGame = bind(this.setStartGame, this);
      this.waitForStart.click.add(this.setStartGame);
    }

    WaitForStart.prototype.setStartGame = function() {
      this.startGame = true;
    };

    return WaitForStart;

  })();

}).call(this);

//# sourceMappingURL=wait_for_start.js.map
