// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  asteroids.components.WaitForStart = (function() {
    WaitForStart.className = 'WaitForStart';

    WaitForStart.prototype.waitForStart = null;

    WaitForStart.prototype.startGame = false;

    function WaitForStart(_at_waitForStart) {
      this.waitForStart = _at_waitForStart;
      this.setStartGame = __bind(this.setStartGame, this);
      this.waitForStart.click.add(this.setStartGame);
    }

    WaitForStart.prototype.setStartGame = function() {
      this.startGame = true;
    };

    return WaitForStart;

  })();

}).call(this);

//# sourceMappingURL=wait_for_start.js.map
