// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  asteroids.input.KeyPoll = (function() {
    KeyPoll.prototype.states = null;

    KeyPoll.prototype.displayObj = null;

    function KeyPoll(_at_displayObj) {
      this.displayObj = _at_displayObj;
      this.isUp = __bind(this.isUp, this);
      this.isDown = __bind(this.isDown, this);
      this.keyUpListener = __bind(this.keyUpListener, this);
      this.keyDownListener = __bind(this.keyDownListener, this);
      this.states = {};
      this.displayObj.addEventListener("keydown", this.keyDownListener);
      this.displayObj.addEventListener("keyup", this.keyUpListener);
    }

    KeyPoll.prototype.keyDownListener = function(event) {
      this.states[event.keyCode] = true;
    };

    KeyPoll.prototype.keyUpListener = function(event) {
      if (this.states[event.keyCode]) {
        this.states[event.keyCode] = false;
      }
    };

    KeyPoll.prototype.isDown = function(keyCode) {
      return this.states[keyCode];
    };

    KeyPoll.prototype.isUp = function(keyCode) {
      return !this.states[keyCode];
    };

    return KeyPoll;

  })();

}).call(this);

//# sourceMappingURL=key_poll.js.map
