// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  asteroids.input.KeyPoll = (function() {
    var displayObj, states;

    states = null;

    displayObj = null;

    function KeyPoll(displayObj1) {
      this.displayObj = displayObj1;
      this.isUp = bind(this.isUp, this);
      this.isDown = bind(this.isDown, this);
      this.keyUpListener = bind(this.keyUpListener, this);
      this.keyDownListener = bind(this.keyDownListener, this);
      this.states = {};
      this.displayObj.addEventListener("keydown", this.keyDownListener);
      this.displayObj.addEventListener("keyup", this.keyUpListener);
    }

    KeyPoll.prototype.keyDownListener = function(event) {
      this.states[event.keyCode] = true;
    };

    KeyPoll.prototype.keyUpListener = function(event) {
      if (this.states[event.keyCode]) {
        this.states[event.keyCode] = false;
      }
    };

    KeyPoll.prototype.isDown = function(keyCode) {
      return this.states[keyCode];
    };

    KeyPoll.prototype.isUp = function(keyCode) {
      return !this.states[keyCode];
    };

    return KeyPoll;

  })();

}).call(this);

//# sourceMappingURL=key_poll.js.map
