// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  ash.fsm.ComponentTypeProvider = (function() {
    ComponentTypeProvider.prototype.componentType = null;


    /*
     * Constructor
     *
     * @param type The type of the single instance
     */

    function ComponentTypeProvider(type) {
      this.componentType = type;
    }


    /*
     * Used to request a component from this provider
     *
     * @return The instance
     */

    ComponentTypeProvider.prototype.getComponent = function() {
      return new this.componentType();
    };


    /*
     * Used to compare this provider with others. Any provider that returns the same component
     * instance will be regarded as equivalent.
     *
     * @return The instance
     */

    Object.defineProperties(ComponentTypeProvider.prototype, {
      identifier: {
        get: function() {
          return this.componentType;
        }
      }
    });

    return ComponentTypeProvider;

  })();

}).call(this);

//# sourceMappingURL=ComponentTypeProvider.js.map
