// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  ash.fsm.ComponentSingletonProvider = (function() {
    ComponentSingletonProvider.prototype.componentType = null;

    ComponentSingletonProvider.prototype.instance = null;


    /*
     * Constructor
     *
     * @param type The type of the single instance
     */

    function ComponentSingletonProvider(type) {
      this.componentType = type;

      /*
       * Used to request a component from this provider
       *
       * @return The instance
       */
    }

    ComponentSingletonProvider.prototype.getComponent = function() {
      if (this.instance == null) {
        this.instance = new this.componentType();
      }
      return this.instance;
    };


    /*
     * Used to compare this provider with others. Any provider that returns the same component
     * instance will be regarded as equivalent.
     *
     * @return The instance
     */

    Object.defineProperties(ComponentSingletonProvider.prototype, {
      identifier: {
        get: function() {
          return this.getComponent();
        }
      }
    });

    return ComponentSingletonProvider;

  })();

}).call(this);

//# sourceMappingURL=ComponentSingletonProvider.js.map
