// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  ash.fsm.ComponentTypeProvider = (function() {

    /**
     * @type {Function}
     */
    ComponentTypeProvider.prototype.componentType = null;


    /**
     * @constructor
     * @param {Function} type The type of the single instance
     */

    function ComponentTypeProvider(type) {
      this.componentType = type;
    }


    /**
     * Used to request a component from this provider
     *
     * @return {Object} The instance
     */

    ComponentTypeProvider.prototype.getComponent = function() {
      return new this.componentType();
    };


    /**
     * Used to compare this provider with others. Any provider that returns the same component
     * instance will be regarded as equivalent.
     *
     * @return {Object} The instance
     */

    ComponentTypeProvider.prototype.getIdentifier = function() {
      return this.componentType;
    };

    return ComponentTypeProvider;

  })();

}).call(this);

//# sourceMappingURL=ComponentTypeProvider.js.map
