// Generated by CoffeeScript 1.9.0
'use strict';
ash.fsm.ComponentSingletonProvider = (function() {

  /**
   * @type {Function}
   */
  ComponentSingletonProvider.prototype.componentType = null;


  /**
   * @type {Object}
   */

  ComponentSingletonProvider.prototype.instance = null;


  /**
   * @constructor
   * @param {Function} type The type of the single instance
   */

  function ComponentSingletonProvider(type) {
    this.componentType = type;
  }


  /**
    * Used to request a component from this provider
    *
    * @return {Object} The instance
   */

  ComponentSingletonProvider.prototype.getComponent = function() {
    if (this.instance == null) {
      this.instance = new this.componentType();
    }
    return this.instance;
  };


  /**
   * Used to compare this provider with others. Any provider that returns the same component
   * instance will be regarded as equivalent.
   *
   * @return {Object} The instance
   */

  Object.defineProperties(ComponentSingletonProvider.prototype, {
    identifier: {
      get: function() {
        return this.getComponent();
      }
    }
  });

  return ComponentSingletonProvider;

})();

//# sourceMappingURL=ComponentSingletonProvider.js.map
