// Generated by CoffeeScript 1.9.3

/*
 * This System provider returns results of a method call. The method
 * is passed to the provider at initialisation.
 */

(function() {
  'use strict';
  ash.fsm.DynamicSystemProvider = (function() {
    DynamicSystemProvider.prototype.method = function() {};

    DynamicSystemProvider.prototype.systemPriority = 0;


    /*
     * Constructor
     *
     * @param method The method that returns the System instance;
     */

    function DynamicSystemProvider(method) {
      this.method = method;
    }


    /*
     * Used to compare this provider with others. Any provider that returns the same component
     * instance will be regarded as equivalent.
     *
     * @return The method used to call the System instances
     */

    DynamicSystemProvider.prototype.getSystem = function() {
      return this.method();
    };

    Object.defineProperties(DynamicSystemProvider.prototype, {

      /*
       * The priority at which the System should be added to the Engine
       */
      identifier: {
        get: function() {
          return this.method;
        }

        /*
         * The priority at which the System should be added to the Engine
         */
      },
      priority: {
        get: function() {
          return this.systemPriority;
        },
        set: function(value) {
          return this.systemPriority = value;
        }
      }
    });

    return DynamicSystemProvider;

  })();

}).call(this);

//# sourceMappingURL=DynamicSystemProvider.js.map
