// Generated by CoffeeScript 1.9.0

/*
 * This System provider returns results of a method call. The method
 * is passed to the provider at initialisation.
 */
'use strict';
ash.fsm.DynamicSystemProvider = (function() {

  /**
   * @type {Function}
   */
  DynamicSystemProvider.prototype.method = function() {};


  /**
   * @type {number}
   */

  DynamicSystemProvider.prototype.systemPriority = 0;


  /**
   * @constructor
   * @param {Function} method The method that returns the System instance;
   */

  function DynamicSystemProvider(_at_method) {
    this.method = _at_method;
  }


  /*
   * Used to compare this provider with others. Any provider that returns the same component
   * instance will be regarded as equivalent.
   *
   * @return {Function} The method used to call the System instances
   */

  DynamicSystemProvider.prototype.getSystem = function() {
    return this.method();
  };

  Object.defineProperties(DynamicSystemProvider.prototype, {

    /*
     * The priority at which the System should be added to the Engine
     * @return {Function}
     */
    identifier: {
      get: function() {
        return this.method;
      }
    },

    /*
     * The priority at which the System should be added to the Engine
     * @return {number}
     */
    priority: {
      get: function() {
        return this.systemPriority;
      },
      set: function(value) {
        return this.systemPriority = value;
      }
    }
  });

  return DynamicSystemProvider;

})();

//# sourceMappingURL=DynamicSystemProvider.js.map
