// Generated by CoffeeScript 1.9.3

/*
 * This System provider always returns the same instance of the component. The system
 * is passed to the provider at initialisation.
 */

(function() {
  'use strict';
  ash.fsm.SystemInstanceProvider = (function() {
    SystemInstanceProvider.prototype.instance = null;

    SystemInstanceProvider.prototype.systemPriority = 0;


    /*
     * Constructor
     *
     * @param instance The instance to return whenever a System is requested.
     */

    function SystemInstanceProvider(instance) {
      this.instance = instance;
    }


    /*
     * Used to request a component from this provider
     *
     * @return The instance of the System
     */

    SystemInstanceProvider.prototype.getSystem = function() {
      return this.instance;
    };

    Object.defineProperties(SystemInstanceProvider.prototype, {

      /*
       * Used to compare this provider with others. Any provider that returns the same component
       * instance will be regarded as equivalent.
       *
       * @return The instance
       */
      identifier: {
        get: function() {
          return this.instance;
        }
      },

      /*
       * The priority at which the System should be added to the Engine
       */
      priority: {
        get: function() {
          return this.systemPriority;
        },
        set: function(value) {
          return this.systemPriority = value;
        }
      }
    });

    return SystemInstanceProvider;

  })();

}).call(this);

//# sourceMappingURL=SystemInstanceProvider.js.map
