// Generated by CoffeeScript 1.9.0

/*
 * This System provider always returns the same instance of the System. The instance
 * is created when first required and is of the type passed in to the constructor.
 */
'use strict';
ash.fsm.SystemSingletonProvider = (function() {

  /**
   * @type {Object}
   */
  SystemSingletonProvider.prototype.componentType = null;


  /**
   * @type {Object}
   */

  SystemSingletonProvider.prototype.instance = null;


  /**
   * @type {number}
   */

  SystemSingletonProvider.prototype.systemPriority = 0;


  /**
   * @constructor
   *
   * @param {Function} type The type of the single System instance
   */

  function SystemSingletonProvider(type) {
    this.componentType = type;
  }


  /**
   * Used to request a System from this provider
   *
   * @return {Object} The single instance
   */

  SystemSingletonProvider.prototype.getSystem = function() {
    if (!this.instance) {
      this.instance = new this.componentType();
    }
    return this.instance;
  };

  Object.defineProperties(SystemSingletonProvider.prototype, {

    /**
    		 * Used to compare this provider with others. Any provider that returns the same single
    		 * instance will be regarded as equivalent.
    		 *
    		 * @type {Object} The single instance
     */
    identifier: {
      get: function() {
        return this.getSystem();
      }
    },

    /**
     * The priority at which the System should be added to the Engine
     * @type {Object}
     */
    priority: {
      get: function() {
        return this.systemPriority;
      },
      set: function(value) {
        return this.systemPriority = value;
      }
    }
  });

  return SystemSingletonProvider;

})();

//# sourceMappingURL=SystemSingletonProvider.js.map
