// Generated by CoffeeScript 1.9.0

/*
 * This System provider always returns the same instance of the System. The instance
 * is created when first required and is of the type passed in to the constructor.
 */

(function() {
  'use strict';
  ash.fsm.SystemSingletonProvider = (function() {

    /**
     * @type {Object}
     */
    SystemSingletonProvider.prototype.componentType = null;


    /**
     * @type {Object}
     */

    SystemSingletonProvider.prototype.instance = null;


    /**
     * @type {number}
     */

    SystemSingletonProvider.prototype.priority = 0;


    /**
     * @constructor
     *
     * @param {Function} type The type of the single System instance
     */

    function SystemSingletonProvider(type) {
      this.componentType = type;
    }


    /**
     * Used to request a System from this provider
     *
     * @return {Object} The single instance
     */

    SystemSingletonProvider.prototype.getSystem = function() {
      if (!this.instance) {
        this.instance = new this.componentType();
      }
      return this.instance;
    };


    /**
     * Used to compare this provider with others. Any provider that returns the same single
     * instance will be regarded as equivalent.
     *
     * @type {Object} The single instance
     */

    SystemSingletonProvider.prototype.getIdentifier = function() {
      return this.getSystem();
    };

    return SystemSingletonProvider;

  })();

}).call(this);

//# sourceMappingURL=SystemSingletonProvider.js.map
