// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.ui.Container = (function() {
    Container.prototype.graphic = null;

    Container.prototype.children = null;

    function Container(graphic) {
      this.graphic = graphic;
      this.children = [];
    }

    Container.prototype.addChild = function(child) {
      return this.children.push(child);
    };

    Container.prototype.draw = function() {
      var child, i, len, results;
      results = [];
      for (i = 0, len = children.length; i < len; i++) {
        child = children[i];
        results.push(child.draw());
      }
      return results;
    };

    return Container;

  })();

}).call(this);

//# sourceMappingURL=container.js.map
