// Generated by CoffeeScript 1.9.0

/*
 * A node in the list of listeners in a signal.
 */

(function() {
  'use strict';

  /**
   * @constructor
   */
  ash.signals.ListenerNode = (function() {
    function ListenerNode() {}


    /**
     * @param {ash.signals.ListenerNode}
     */

    ListenerNode.prototype.previous = null;


    /**
     * @param {ash.signals.ListenerNode}
     */

    ListenerNode.prototype.next = null;


    /**
     * @param {ash.signals.SignalBase}
     */

    ListenerNode.prototype.listener = null;


    /**
     * @param {boolean}
     */

    ListenerNode.prototype.once = false;

    return ListenerNode;

  })();

}).call(this);

//# sourceMappingURL=ListenerNode.js.map
