// Generated by CoffeeScript 1.9.3

/*
 * A node in the list of listeners in a signal.
 */

(function() {
  'use strict';
  ash.signals.ListenerNode = (function() {
    function ListenerNode() {}

    ListenerNode.prototype.previous = null;

    ListenerNode.prototype.next = null;

    ListenerNode.prototype.listener = null;

    ListenerNode.prototype.once = false;

    return ListenerNode;

  })();

}).call(this);

//# sourceMappingURL=ListenerNode.js.map
