// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ash.signals.Signal3 = (function(superClass) {
    extend(Signal3, superClass);

    function Signal3() {
      return Signal3.__super__.constructor.apply(this, arguments);
    }

    Signal3.prototype.dispatch = function($1, $2, $3) {
      var node;
      this.startDispatch();
      node = this.head;
      while (node !== null) {
        node.listener($1, $2, $3);
        if (node.once) {
          this.remove(node.listener);
        }
        node = node.next;
      }
      return this.endDispatch();
    };

    return Signal3;

  })(ash.signals.SignalBase);

}).call(this);

//# sourceMappingURL=Signal3.js.map
