// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /**
   * @extends {ash.signals.SignalBase}
   * @constructor
   */
  var __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  ash.signals.Signal1 = (function(_super) {
    __extends(Signal1, _super);

    function Signal1() {
      return Signal1.__super__.constructor.apply(this, arguments);
    }


    /**
     * dispatch the event
     * @param {any}
     */

    Signal1.prototype.dispatch = function($1) {
      var node;
      this.startDispatch();
      node = this.head;
      while (node !== null) {
        node.listener($1);
        if (node.once) {
          this.remove(node.listener);
        }
        node = node.next;
      }
      return this.endDispatch();
    };

    return Signal1;

  })(ash.signals.SignalBase);

}).call(this);

//# sourceMappingURL=Signal1.js.map
