// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  asteroids.GameConfig = (function() {
    function GameConfig() {}

    GameConfig.prototype.width = 0;

    GameConfig.prototype.height = 0;

    return GameConfig;

  })();

}).call(this);

//# sourceMappingURL=game_config.js.map
