// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';

  /**
   * @constructor
   */
  asteroids.GameConfig = (function() {
    function GameConfig() {}


    /** @type {number} */

    GameConfig.prototype.width = 0;


    /** @type {number} */

    GameConfig.prototype.height = 0;

    return GameConfig;

  })();

}).call(this);

//# sourceMappingURL=game_config.js.map
