// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  this.asteroids = (function() {
    function asteroids() {}

    asteroids.input = {};

    asteroids.ui = {};

    asteroids.graphics = {};

    asteroids.components = {};

    asteroids.nodes = {};

    asteroids.systems = {};

    return asteroids;

  })();

}).call(this);

//# sourceMappingURL=index.js.map
