// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var Asteroids;

  Asteroids = asteroids.Asteroids;

  asteroids.Main = (function() {

    /**
     * Create a new game
     * @constructor
     */
    function Main() {
      var canvas;
      canvas = this.canvas();
      new Asteroids(canvas.getContext('2d'), canvas.width, canvas.height).start();
      return;
    }


    /**
     * Create the canvas
     * @return {HTMLCanvasElement}
     */

    Main.prototype.canvas = function() {
      var canvas;
      canvas = document.createElement(navigator.isCocoonJS ? 'screencanvas' : 'canvas');
      canvas.width = window.innerWidth * window.devicePixelRatio;
      canvas.height = window.innerHeight * window.devicePixelRatio;
      canvas.style.width = '100%';
      canvas.style.height = '100%';
      canvas.style.backgroundColor = '#000000';
      document.body.appendChild(canvas);
      return canvas;
    };

    return Main;

  })();

}).call(this);

//# sourceMappingURL=main.js.map
