// Generated by CoffeeScript 1.9.0

/*
 * Uses the enter frame event to provide a frame tick where the frame duration is the time since the previous frame.
 * There is a maximum frame time parameter in the constructor that can be used to limit
 * the longest period a frame can be.
 */
'use strict';
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

ash.tick.FrameTickProvider = (function(_super) {
  __extends(FrameTickProvider, _super);


  /**
   * @type {Object}
   */

  FrameTickProvider.prototype.displayObject = null;


  /**
   * @type {number}
   */

  FrameTickProvider.prototype.previousTime = 0;


  /**
   * @type {number}
   */

  FrameTickProvider.prototype.maximumFrameTime = 0;


  /**
   * @type {boolean}
   */

  FrameTickProvider.prototype.isPlaying = false;


  /**
   * @type {Object}
   */

  FrameTickProvider.prototype.request = null;


  /**
   * Applies a time adjustement factor to the tick, so you can slow down or speed up the entire engine.
   * The update tick time is multiplied by this value, so a value of 1 will run the engine at the normal rate.
   * @type {number}
   */

  FrameTickProvider.prototype.timeAdjustment = 1;


  /**
   * @extends {ash.signals.Signal1}
   * @constructor
   * @param {Object} displayObject
   * @param {number} maximumFrameTime
   */

  function FrameTickProvider(_at_displayObject, _at_maximumFrameTime) {
    this.displayObject = _at_displayObject;
    this.maximumFrameTime = _at_maximumFrameTime;
    this.dispatchTick = __bind(this.dispatchTick, this);
    FrameTickProvider.__super__.constructor.apply(this, arguments);
  }


  /**
   * Is Playing?
   * @return {boolean}
   */

  Object.defineProperties(FrameTickProvider.prototype, {
    playing: {
      get: function() {
        return this.isPlaying;
      }
    }
  });


  /**
   * Start
   */

  FrameTickProvider.prototype.start = function() {
    this.request = requestAnimationFrame(this.dispatchTick);
    this.isPlaying = true;
  };


  /**
   * Stop
   */

  FrameTickProvider.prototype.stop = function() {
    cancelRequestAnimationFrame(this.request);
    this.isPlaying = false;
  };


  /**
   * dispatchTick
   @param {number} timestamp
   */

  FrameTickProvider.prototype.dispatchTick = function(timestamp) {
    var frameTime, temp;
    if (timestamp == null) {
      timestamp = Date.now();
    }
    if (this.displayObject) {
      this.displayObject.begin();
    }
    temp = this.previousTime || timestamp;
    this.previousTime = timestamp;
    frameTime = (timestamp - temp) * 0.001;
    this.dispatch(frameTime);
    requestAnimationFrame(this.dispatchTick);
    if (this.displayObject) {
      this.displayObject.end();
    }
  };

  return FrameTickProvider;

})(ash.signals.Signal1);
