// Generated by CoffeeScript 1.9.0

/*
 * This component provider always returns the same instance of the component. The instance
 * is passed to the provider at initialisation.
 */
'use strict';
ash.fsm.ComponentInstanceProvider = (function() {

  /**
   * @type {Object}
   */
  ComponentInstanceProvider.prototype.instance = null;


  /**
   * @constructor
   * @param {Object} instance The instance to return whenever a component is requested.
   */

  function ComponentInstanceProvider(_at_instance) {
    this.instance = _at_instance;
  }


  /**
   * Used to request a component from this provider
   *
   * @return {Object} The instance
   */

  ComponentInstanceProvider.prototype.getComponent = function() {
    return this.instance;
  };


  /**
   * Used to compare this provider with others. Any provider that returns the same component
   * instance will be regarded as equivalent.
   *
   * @return {Object} The instance
   */

  Object.defineProperties(ComponentInstanceProvider.prototype, {
    identifier: {
      get: function() {
        return this.instance;
      }
    }
  });

  return ComponentInstanceProvider;

})();
