// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var AnimationNode,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  AnimationNode = asteroids.nodes.AnimationNode;

  asteroids.systems.AnimationSystem = (function(superClass) {
    extend(AnimationSystem, superClass);

    function AnimationSystem() {
      this.updateNode = bind(this.updateNode, this);
      AnimationSystem.__super__.constructor.call(this, AnimationNode, this.updateNode);
    }

    AnimationSystem.prototype.updateNode = function(node, time) {
      node.animation.animation.animate(time);
    };

    return AnimationSystem;

  })(ash.tools.ListIteratingSystem);

}).call(this);

//# sourceMappingURL=animation_system.js.map
