// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var BulletAgeNode,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BulletAgeNode = asteroids.nodes.BulletAgeNode;

  asteroids.systems.BulletAgeSystem = (function(superClass) {
    extend(BulletAgeSystem, superClass);

    BulletAgeSystem.prototype.creator = null;

    function BulletAgeSystem(creator) {
      this.creator = creator;
      this.updateNode = bind(this.updateNode, this);
      BulletAgeSystem.__super__.constructor.call(this, BulletAgeNode, this.updateNode);
    }

    BulletAgeSystem.prototype.updateNode = function(node, time) {
      var bullet;
      bullet = node.bullet;
      bullet.lifeRemaining -= time;
      if (bullet.lifeRemaining <= 0) {
        this.creator.destroyEntity(node.entity);
      }
    };

    return BulletAgeSystem;

  })(ash.tools.ListIteratingSystem);

}).call(this);

//# sourceMappingURL=bullet_age_system.js.map
