// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var BulletAgeNode,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  BulletAgeNode = asteroids.nodes.BulletAgeNode;

  asteroids.systems.BulletAgeSystem = (function(_super) {
    __extends(BulletAgeSystem, _super);


    /** @type {asteroids.EntityCreator} */

    BulletAgeSystem.prototype.creator = null;


    /**
     * @constructor
     * @param {asteroids.EntityCreator}
     */

    function BulletAgeSystem(_at_creator) {
      this.creator = _at_creator;
      this.updateNode = __bind(this.updateNode, this);
      BulletAgeSystem.__super__.constructor.call(this, BulletAgeNode, this.updateNode);
    }


    /**
     * @param {ash.core.Node}
     * @param {number}
     */

    BulletAgeSystem.prototype.updateNode = function(node, time) {
      var bullet;
      bullet = node.bullet;
      bullet.lifeRemaining -= time;
      if (bullet.lifeRemaining <= 0) {
        this.creator.destroyEntity(node.entity);
      }
    };

    return BulletAgeSystem;

  })(ash.tools.ListIteratingSystem);

}).call(this);

//# sourceMappingURL=bullet_age_system.js.map
