// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var DeathThroesNode,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DeathThroesNode = asteroids.nodes.DeathThroesNode;

  asteroids.systems.DeathThroesSystem = (function(superClass) {
    extend(DeathThroesSystem, superClass);

    DeathThroesSystem.prototype.creator = null;

    function DeathThroesSystem(creator) {
      this.creator = creator;
      this.updateNode = bind(this.updateNode, this);
      DeathThroesSystem.__super__.constructor.call(this, DeathThroesNode, this.updateNode);
    }

    DeathThroesSystem.prototype.updateNode = function(node, time) {
      node.death.countdown -= time;
      if (node.death.countdown <= 0) {
        this.creator.destroyEntity(node.entity);
      }
    };

    return DeathThroesSystem;

  })(ash.tools.ListIteratingSystem);

}).call(this);

//# sourceMappingURL=death_throes_system.js.map
