// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var HudNode,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  HudNode = asteroids.nodes.HudNode;

  asteroids.systems.HudSystem = (function(superClass) {
    extend(HudSystem, superClass);

    function HudSystem() {
      this.updateNode = bind(this.updateNode, this);
      HudSystem.__super__.constructor.call(this, HudNode, this.updateNode);
    }

    HudSystem.prototype.updateNode = function(node, time) {
      node.hud.view.setLives(node.state.lives);
      node.hud.view.setScore(node.state.hits);
    };

    return HudSystem;

  })(ash.tools.ListIteratingSystem);

}).call(this);

//# sourceMappingURL=hud_system.js.map
