// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var MotionControlNode, b2Vec2,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  MotionControlNode = asteroids.nodes.MotionControlNode;

  b2Vec2 = Box2D.Common.Math.b2Vec2;

  asteroids.systems.MotionControlSystem = (function(superClass) {
    extend(MotionControlSystem, superClass);

    MotionControlSystem.prototype.keyPoll = null;

    function MotionControlSystem(keyPoll) {
      this.keyPoll = keyPoll;
      this.updateNode = bind(this.updateNode, this);
      MotionControlSystem.__super__.constructor.call(this, MotionControlNode, this.updateNode);
    }

    MotionControlSystem.prototype.updateNode = function(node, time) {
      var control, left, motion, position, right;
      control = node.control;
      position = node.position;
      motion = node.motion;
      left = this.keyPoll.isDown(control.left);
      right = this.keyPoll.isDown(control.right);
      if (left) {
        position.rotation -= control.rotationRate * time;
      }
      if (right) {
        position.rotation += control.rotationRate * time;
      }
      if (this.keyPoll.isDown(control.accelerate)) {
        motion.velocity.x += Math.cos(position.rotation) * control.accelerationRate * time;
        motion.velocity.y += Math.sin(position.rotation) * control.accelerationRate * time;
      }
    };

    return MotionControlSystem;

  })(ash.tools.ListIteratingSystem);

}).call(this);

//# sourceMappingURL=motion_control_system.js.map
