// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var MotionControlNode,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  MotionControlNode = asteroids.nodes.MotionControlNode;

  asteroids.systems.MotionControlSystem = (function(_super) {
    __extends(MotionControlSystem, _super);


    /** @type {asteroids.input.KeyPoll} */

    MotionControlSystem.prototype.keyPoll = null;


    /**
     * @constructor
     * @extends {ash.tools.ListIteratingSystem}
     * @param {asteroids.input.KeyPoll}
     */

    function MotionControlSystem(_at_keyPoll) {
      this.keyPoll = _at_keyPoll;
      this.updateNode = __bind(this.updateNode, this);
      MotionControlSystem.__super__.constructor.call(this, MotionControlNode, this.updateNode);
    }


    /**
     * @param {ash.core.Node}
     * @param {number}
     */

    MotionControlSystem.prototype.updateNode = function(node, time) {
      var control, left, motion, position, right;
      control = node.control;
      position = node.position;
      motion = node.motion;
      left = this.keyPoll.isDown(control.left);
      right = this.keyPoll.isDown(control.right);
      if (left) {
        position.rotation -= control.rotationRate * time;
      }
      if (right) {
        position.rotation += control.rotationRate * time;
      }
      if (this.keyPoll.isDown(control.accelerate)) {
        motion.velocity.x += Math.cos(position.rotation) * control.accelerationRate * time;
        motion.velocity.y += Math.sin(position.rotation) * control.accelerationRate * time;
      }
    };

    return MotionControlSystem;

  })(ash.tools.ListIteratingSystem);

}).call(this);

//# sourceMappingURL=motion_control_system.js.map
