// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  var RenderNode,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  RenderNode = asteroids.nodes.RenderNode;

  asteroids.systems.RenderSystem = (function(_super) {
    __extends(RenderSystem, _super);


    /** @type {CanvasRenderingContext2D} */

    RenderSystem.prototype.graphic = null;


    /** @type {ash.core.NodeList} */

    RenderSystem.prototype.nodes = null;


    /**
     * @constructor
     * @extends {ash.core.System}
     * @param {CanvasRenderingContext2D}
     */

    function RenderSystem(_at_graphic) {
      this.graphic = _at_graphic;
      this.update = __bind(this.update, this);
    }


    /**
     * @param {ash.core.Engine}
     */

    RenderSystem.prototype.addToEngine = function(engine) {
      var node;
      this.nodes = engine.getNodeList(RenderNode);
      node = this.nodes.head;
      while (node) {
        this.addToDisplay(node);
        node = node.next;
      }
    };


    /**
     * @param {ash.core.Node}
     */

    RenderSystem.prototype.addToDisplay = function(node) {};


    /**
     * @param {ash.core.Node}
     */

    RenderSystem.prototype.removeFromDisplay = function(node) {};


    /**
     * @param {ash.core.Engine}
     */

    RenderSystem.prototype.removeFromEngine = function(engine) {
      this.nodes = null;
    };


    /**
     * @param {number}
     */

    RenderSystem.prototype.update = function(time) {
      var display, graphic, node, position;
      this.graphic.save();
      this.graphic.translate(0, 0);
      this.graphic.rotate(0);
      this.graphic.clearRect(0, 0, this.graphic.canvas.width, this.graphic.canvas.height);
      node = this.nodes.head;
      while (node) {
        display = node.display;
        graphic = display.graphic;
        position = node.position;
        graphic.x = position.position.x;
        graphic.y = position.position.y;
        graphic.rotation = position.rotation;
        graphic.draw();
        node = node.next;
      }
      this.graphic.restore();
    };

    return RenderSystem;

  })(ash.core.System);

}).call(this);

//# sourceMappingURL=render_system.js.map
