// Generated by CoffeeScript 1.9.0
(function() {
  'use strict';
  asteroids.systems.SystemPriorities = (function() {
    function SystemPriorities() {}

    SystemPriorities.preUpdate = 1;

    SystemPriorities.update = 2;

    SystemPriorities.move = 3;

    SystemPriorities.resolveCollisions = 4;

    SystemPriorities.stateMachines = 5;

    SystemPriorities.animate = 6;

    SystemPriorities.render = 7;

    return SystemPriorities;

  })();

}).call(this);

//# sourceMappingURL=system_priorities.js.map
