// Generated by CoffeeScript 1.9.0

/*
 * A Helper for Components & Nodes
 *
 * Creates a common registry object
 * Fix-up up Node templates
 */

(function() {
  'use strict';

  /**
   * @constructor
   * @dict
   */
  ash.ext.Dictionary = (function() {
    function Dictionary() {}

    return Dictionary;

  })();

}).call(this);

//# sourceMappingURL=Dictionary.js.map
