// Generated by CoffeeScript 1.9.3

/*
 * A Helper for Components & Nodes
 *
 * Creates a common registry object
 * Fix-up up Node templates
 */

(function() {
  'use strict';
  var hasProp = {}.hasOwnProperty;

  ash.ext.Helper = (function() {
    Helper.prototype.components = null;

    Helper.prototype.nodes = null;

    function Helper(components, nodes) {
      var klass, name, property, ref, type;
      this.components = {};
      this.nodes = {};

      /*
       * register components
       */
      if (components != null) {
        for (name in components) {
          klass = components[name];
          this.components[name] = klass;
        }
      }

      /*
       * register nodes
       */
      if (nodes != null) {
        for (name in nodes) {
          klass = nodes[name];

          /*
           * convert template to an actual node class
           */
          if (klass.components == null) {
            klass.components = {};
            ref = klass.prototype;
            for (property in ref) {
              if (!hasProp.call(ref, property)) continue;
              type = ref[property];
              klass.components[property] = type;
              klass.prototype[property] = null;
            }
            klass.prototype.entity = null;
            klass.prototype.previous = null;
            klass.prototype.next = null;
          }
          if (components != null) {
            this.nodes[name] = klass;
          }
        }
      }
    }

    return Helper;

  })();

}).call(this);

//# sourceMappingURL=Helper.js.map
