// Generated by CoffeeScript 1.9.0

/**
 * @constructor
 */

(function() {
  ash.ext.Util = (function() {
    function Util() {}


    /**
    	 * Get Class Name
    	 *
    	 * closure compiler changes the class name, or sets it to ''
    	 * In that case, add a static className property to all
    	 * Nodes and Components so they can be identified.
    	 *
    	 * @param {Function} klass
    	 * @return {string}
     */

    Util.getClassName = function(klass) {
      var _ref;
      return (_ref = klass.className) != null ? _ref : klass.name;
    };

    return Util;

  })();

}).call(this);

//# sourceMappingURL=Util.js.map
